// Code generated by goctl. DO NOT EDIT!
// Source: product.proto

package productclient

import (
	"context"

	"github.com/smartgreeting/store-rpc/product/product"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Banner                = product.Banner
	BannerReply           = product.BannerReply
	DeleteProductReply    = product.DeleteProductReply
	DeleteProductReq      = product.DeleteProductReq
	GetBannerReq          = product.GetBannerReq
	GetProductListReq     = product.GetProductListReq
	GetProductReq         = product.GetProductReq
	IncrementProductReply = product.IncrementProductReply
	ProductListReply      = product.ProductListReply
	ProductReply          = product.ProductReply
	ProductReq            = product.ProductReq
	UpdateProductReply    = product.UpdateProductReply

	Product interface {
		//  获取轮播图
		GetBanner(ctx context.Context, in *GetBannerReq, opts ...grpc.CallOption) (*BannerReply, error)
		// 获取产品
		GetProduct(ctx context.Context, in *GetProductReq, opts ...grpc.CallOption) (*ProductReply, error)
		//  获取产品列表
		GetProductList(ctx context.Context, in *GetProductListReq, opts ...grpc.CallOption) (*ProductListReply, error)
		//  新增产品
		IncrementProduct(ctx context.Context, in *ProductReq, opts ...grpc.CallOption) (*IncrementProductReply, error)
		//  修改产品
		UpdateProduct(ctx context.Context, in *ProductReq, opts ...grpc.CallOption) (*UpdateProductReply, error)
		//  删除商品
		DeleteProduct(ctx context.Context, in *DeleteProductReq, opts ...grpc.CallOption) (*DeleteProductReply, error)
	}

	defaultProduct struct {
		cli zrpc.Client
	}
)

func NewProduct(cli zrpc.Client) Product {
	return &defaultProduct{
		cli: cli,
	}
}

//  获取轮播图
func (m *defaultProduct) GetBanner(ctx context.Context, in *GetBannerReq, opts ...grpc.CallOption) (*BannerReply, error) {
	client := product.NewProductClient(m.cli.Conn())
	return client.GetBanner(ctx, in, opts...)
}

// 获取产品
func (m *defaultProduct) GetProduct(ctx context.Context, in *GetProductReq, opts ...grpc.CallOption) (*ProductReply, error) {
	client := product.NewProductClient(m.cli.Conn())
	return client.GetProduct(ctx, in, opts...)
}

//  获取产品列表
func (m *defaultProduct) GetProductList(ctx context.Context, in *GetProductListReq, opts ...grpc.CallOption) (*ProductListReply, error) {
	client := product.NewProductClient(m.cli.Conn())
	return client.GetProductList(ctx, in, opts...)
}

//  新增产品
func (m *defaultProduct) IncrementProduct(ctx context.Context, in *ProductReq, opts ...grpc.CallOption) (*IncrementProductReply, error) {
	client := product.NewProductClient(m.cli.Conn())
	return client.IncrementProduct(ctx, in, opts...)
}

//  修改产品
func (m *defaultProduct) UpdateProduct(ctx context.Context, in *ProductReq, opts ...grpc.CallOption) (*UpdateProductReply, error) {
	client := product.NewProductClient(m.cli.Conn())
	return client.UpdateProduct(ctx, in, opts...)
}

//  删除商品
func (m *defaultProduct) DeleteProduct(ctx context.Context, in *DeleteProductReq, opts ...grpc.CallOption) (*DeleteProductReply, error) {
	client := product.NewProductClient(m.cli.Conn())
	return client.DeleteProduct(ctx, in, opts...)
}
