// Code generated by goctl. DO NOT EDIT!
// Source: product.proto

package productclient

import (
	"context"

	"github.com/smartgreeting/store-rpc/product/product"

	"github.com/tal-tech/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Banner       = product.Banner
	BannerReply  = product.BannerReply
	GetBannerReq = product.GetBannerReq

	Product interface {
		//  获取轮播图
		GetBanner(ctx context.Context, in *GetBannerReq, opts ...grpc.CallOption) (*BannerReply, error)
	}

	defaultProduct struct {
		cli zrpc.Client
	}
)

func NewProduct(cli zrpc.Client) Product {
	return &defaultProduct{
		cli: cli,
	}
}

//  获取轮播图
func (m *defaultProduct) GetBanner(ctx context.Context, in *GetBannerReq, opts ...grpc.CallOption) (*BannerReply, error) {
	client := product.NewProductClient(m.cli.Conn())
	return client.GetBanner(ctx, in, opts...)
}
