// Code generated by goctl. DO NOT EDIT!
// Source: user.proto

package server

import (
	"context"

	"github.com/smartgreeting/store-rpc/user/internal/logic"
	"github.com/smartgreeting/store-rpc/user/internal/svc"
	"github.com/smartgreeting/store-rpc/user/user"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

//  获取短信验证码
func (s *UserServer) GetSms(ctx context.Context, in *user.GetSmsReq) (*user.UserReply, error) {
	l := logic.NewGetSmsLogic(ctx, s.svcCtx)
	return l.GetSms(in)
}
