// Code generated by goctl. DO NOT EDIT!
// Source: product.proto

package server

import (
	"context"

	"github.com/smartgreeting/store-rpc/product/internal/logic"
	"github.com/smartgreeting/store-rpc/product/internal/svc"
	"github.com/smartgreeting/store-rpc/product/product"
)

type ProductServer struct {
	svcCtx *svc.ServiceContext
}

func NewProductServer(svcCtx *svc.ServiceContext) *ProductServer {
	return &ProductServer{
		svcCtx: svcCtx,
	}
}

//  获取轮播图
func (s *ProductServer) GetBanner(ctx context.Context, in *product.GetBannerReq) (*product.BannerReply, error) {
	l := logic.NewGetBannerLogic(ctx, s.svcCtx)
	return l.GetBanner(in)
}
