// Code generated by goctl. DO NOT EDIT!
// Source: product.proto

package server

import (
	"context"

	"github.com/smartgreeting/store-rpc/product/internal/logic"
	"github.com/smartgreeting/store-rpc/product/internal/svc"
	"github.com/smartgreeting/store-rpc/product/product"
)

type ProductServer struct {
	svcCtx *svc.ServiceContext
}

func NewProductServer(svcCtx *svc.ServiceContext) *ProductServer {
	return &ProductServer{
		svcCtx: svcCtx,
	}
}

//  获取轮播图
func (s *ProductServer) GetBanner(ctx context.Context, in *product.GetBannerReq) (*product.BannerReply, error) {
	l := logic.NewGetBannerLogic(ctx, s.svcCtx)
	return l.GetBanner(in)
}

// 获取产品
func (s *ProductServer) GetProduct(ctx context.Context, in *product.GetProductReq) (*product.ProductReply, error) {
	l := logic.NewGetProductLogic(ctx, s.svcCtx)
	return l.GetProduct(in)
}

//  获取产品列表
func (s *ProductServer) GetProductList(ctx context.Context, in *product.GetProductListReq) (*product.ProductListReply, error) {
	l := logic.NewGetProductListLogic(ctx, s.svcCtx)
	return l.GetProductList(in)
}
