// Code generated by goctl. DO NOT EDIT!
// Source: seckill.proto

package server

import (
	"context"

	"github.com/smartgreeting/store-rpc/seckill/internal/logic"
	"github.com/smartgreeting/store-rpc/seckill/internal/svc"
	"github.com/smartgreeting/store-rpc/seckill/seckill"
)

type SeckillServer struct {
	svcCtx *svc.ServiceContext
}

func NewSeckillServer(svcCtx *svc.ServiceContext) *SeckillServer {
	return &SeckillServer{
		svcCtx: svcCtx,
	}
}

//  获取首页秒杀列表
func (s *SeckillServer) GetSeckillHomeList(ctx context.Context, in *seckill.GetSeckillHomeReq) (*seckill.GetSeckillHomeListReply, error) {
	l := logic.NewGetSeckillHomeListLogic(ctx, s.svcCtx)
	return l.GetSeckillHomeList(in)
}

//  获取秒杀列表
func (s *SeckillServer) GetSeckillList(ctx context.Context, in *seckill.GetSeckillReq) (*seckill.GetSeckillListReply, error) {
	l := logic.NewGetSeckillListLogic(ctx, s.svcCtx)
	return l.GetSeckillList(in)
}
