// Code generated by goctl. DO NOT EDIT!
// Source: user.proto

package userclient

import (
	"context"

	"github.com/smartgreeting/store-rpc/user/user"

	"github.com/tal-tech/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetSmsReq = user.GetSmsReq
	UserReply = user.UserReply

	User interface {
		//  获取短信验证码
		GetSms(ctx context.Context, in *GetSmsReq, opts ...grpc.CallOption) (*UserReply, error)
	}

	defaultUser struct {
		cli zrpc.Client
	}
)

func NewUser(cli zrpc.Client) User {
	return &defaultUser{
		cli: cli,
	}
}

//  获取短信验证码
func (m *defaultUser) GetSms(ctx context.Context, in *GetSmsReq, opts ...grpc.CallOption) (*UserReply, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.GetSms(ctx, in, opts...)
}
